// Generated by `bun init`

declare module "*.svg" {
	/**
	 * A path to the SVG file
	 */
	const path: `${string}.svg`;
	export = path;
}

declare module "*.module.css" {
	/**
	 * A record of class names to their corresponding CSS module classes
	 */
	const classes: { readonly [key: string]: string };
	export = classes;
}

declare module "*.md" {
	/**
	 * The content of the Markdown file as a string
	 */
	const content: string;
	export = content;
}
