export const PW_WEBAPP_BASE_URL = "http://localhost:3000";
export const PW_DAEMON_BASE_URL = "http://localhost:56499";

export const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export const HEADER_LOGO_TEST_ID = "__HEADER_LOGO_TEST_ID";
export const DISCOVER_BUTTON_TEST_ID = "__DISCOVER_BUTTON_TEST_ID";
export const LIBRARY_BUTTON_TEST_ID = "__LIBRARY_BUTTON_TEST_ID";
export const SETTINGS_BUTTON_TEST_ID = "__SETTINGS_BUTTON_TEST_ID";
export const LOGIN_BUTTON_TEST_ID = "__LOGIN_BUTTON_TEST_ID";

export const STAT_CARD_TOTAL_MODS_TEST_ID = "__STAT_CARD_TOTAL_MODS_TEST_ID";
export const STAT_CARD_TOTAL_DOWNLOADS_TEST_ID = "__STAT_CARD_TOTAL_DOWNLOADS_TEST_ID";
export const STAT_CARD_DOWNLOADS_TEST_ID = "__STAT_CARD_DOWNLOADS_TEST_ID";
export const STAT_CARD_ENABLED_TEST_ID = "__STAT_CARD_ENABLED_TEST_ID";
export const STAT_CARD_UPDATES_TEST_ID = "__STAT_CARD_UPDATES_TEST_ID";

export const FEATURED_MODS_SECTION_TEST_ID = "__FEATURED_MODS_SECTION_TEST_ID";
export const POPULAR_MODS_SECTION_TEST_ID = "__POPULAR_MODS_SECTION_TEST_ID";
