export const HEADER_LOGO_TEST_ID = "__HEADER_LOGO_TEST_ID";
export const DISCOVER_BUTTON_TEST_ID = "__DISCOVER_BUTTON_TEST_ID";
export const LIBRARY_BUTTON_TEST_ID = "__LIBRARY_BUTTON_TEST_ID";
export const SETTINGS_BUTTON_TEST_ID = "__SETTINGS_BUTTON_TEST_ID";
export const LOGIN_BUTTON_TEST_ID = "__LOGIN_BUTTON_TEST_ID";

export const STAT_CARD_TOTAL_MODS_TEST_ID = "__STAT_CARD_TOTAL_MODS_TEST_ID";
export const STAT_CARD_TOTAL_DOWNLOADS_TEST_ID = "__STAT_CARD_TOTAL_DOWNLOADS_TEST_ID";
export const STAT_CARD_DOWNLOADS_TEST_ID = "__STAT_CARD_DOWNLOADS_TEST_ID";
export const STAT_CARD_ENABLED_TEST_ID = "__STAT_CARD_ENABLED_TEST_ID";
export const STAT_CARD_UPDATES_TEST_ID = "__STAT_CARD_UPDATES_TEST_ID";

export const FEATURED_MODS_SECTION_TEST_ID = "__FEATURED_MODS_SECTION_TEST_ID";
export const POPULAR_MODS_SECTION_TEST_ID = "__POPULAR_MODS_SECTION_TEST_ID";

export const MY_MODS_BUTTON_TEST_ID = "__MY_MODS_BUTTON_TEST_ID";
export const DASHBOARD_BUTTON_TEST_ID = "__DASHBOARD_BUTTON_TEST_ID";
export const BROWSE_MODS_BUTTON_TEST_ID = "__BROWSE_MODS_BUTTON_TEST_ID";

export const DOWNLOADED_BUTTON_TEST_ID = "__DOWNLOADED_BUTTON_TEST_ID";
export const ENABLED_BUTTON_TEST_ID = "__ENABLED_BUTTON_TEST_ID";
export const UPDATES_BUTTON_TEST_ID = "__UPDATES_BUTTON_TEST_ID";

export const USER_MODS_PUBLISHED_MODS_TEST_ID = "__USER_MODS_PUBLISHED_MODS_TEST_ID";
export const USER_MODS_TOTAL_DOWNLOADS_TEST_ID = "__USER_MODS_TOTAL_DOWNLOADS_TEST_ID";
export const USER_MODS_PUBLISH_NEW_MOD_BTN_TEST_ID = "__USER_MODS_PUBLISH_NEW_MOD_BTN_TEST_ID";

export const NEW_MOD_NAME_TEST_ID = "__NEW_MOD_NAME_TEST_ID";
export const NEW_MOD_DESCRIPTION_TEST_ID = "__NEW_MOD_DESCRIPTION_TEST_ID";
export const NEW_MOD_CATEGORY_TEST_ID = "__NEW_MOD_CATEGORY_TEST_ID";
export const NEW_MOD_SUBMIT_TEST_ID = "__NEW_MOD_SUBMIT_TEST_ID";

export const USER_MOD_FORM_TEST_ID = "__USER_MOD_FORM_TEST_ID";
export const MOD_VISIBILITY_TEST_ID = "__MOD_VISIBILITY_TEST_ID";
export const MOD_SAVE_CHANGES_TEST_ID = "__MOD_SAVE_CHANGES_TEST_ID";
export const MOD_BACK_TO_MODS_TEST_ID = "__MOD_BACK_TO_MODS_TEST_ID";
export const MOD_DELETE_TEST_ID = "__MOD_DELETE_TEST_ID";
export const MOD_DELETE_CONFIRM_TEST_ID = "__MOD_DELETE_CONFIRM_TEST_ID";

export const BROWSE_MODS_TITLE_TEST_ID = "__BROWSE_MODS_TITLE_TEST_ID";
export const BROWSE_MODS_NO_MODS_FOUND_TEST_ID = "__BROWSE_MODS_NO_MODS_FOUND_TEST_ID";
export const MOD_CARD_TEST_ID = (key: string) => `__MOD_CARD_TEST_ID-${key}`;

export const NEW_RELEASE_BUTTON_TEST_ID = "__NEW_RELEASE_BUTTON_TEST_ID";
export const NEW_RELEASE_VERSION_TEST_ID = "__NEW_RELEASE_VERSION_TEST_ID";
export const CREATE_RELEASE_SUBMIT_TEST_ID = "__CREATE_RELEASE_SUBMIT_TEST_ID";
export const RELEASE_VERSION_TEST_ID = "__RELEASE_VERSION_TEST_ID";
export const RELEASE_SAVE_CHANGES_TEST_ID = "__RELEASE_SAVE_CHANGES_TEST_ID";
export const RELEASE_BACK_TO_MOD_TEST_ID = "__RELEASE_BACK_TO_MOD_TEST_ID";
