export enum ModCategory {
	CAMPAIGN = "CAMPAIGN",
	DEVICE_PROFILES = "DEVICE_PROFILES",
	MOD = "MOD",
	MISSION = "MISSION",
	SKIN = "SKIN",
	SOUND = "SOUND",
	TERRAIN = "TERRAIN",
	UTILITY = "UTILITY",
	OTHER = "OTHER",
}
