import { beforeAll, describe, expect, it } from "bun:test";
import { generateDropzoneMissionScriptingScript } from "./generateDropzoneMissionScriptingScript";

describe("generateDropzoneMissionScriptingScript", () => {
	let result: string;
	beforeAll(async () => {
		const paths = [
			{
				id: "example-mod",
				path: "C:/Users/username/Saved Games/DCS/Mods/Scripts/example.lua",
			},
			{
				id: "example-mod-2",
				path: "C:/Users/username/Saved Games/DCS/Mods/Scripts/example2.lua",
			},
		];

		result = await generateDropzoneMissionScriptingScript(paths);
	});

	it("should generate a valid script", () => {
		expect(result).toMatchInlineSnapshot(`
      "-- This file is automatically generated by DCS DROPZONE
      -- Do not edit this file manually as it will be overwritten

      function dofileifexist(filePath)
          local file = io.open(filePath, "r")
          if file then
              env.info("[dcs-dropzone] - Running dofile: " .. filePath)
              file:close()
              dofile(filePath)
          else
              env.warning("[dcs-dropzone] - Attempted to dofile but file was not found: " .. filePath)
          end
      end

      -- ## Start of Scripts ##
      -- example-mod
      dofileifexist([[C:/Users/username/Saved Games/DCS/Mods/Scripts/example.lua]])
      
      -- example-mod-2
      dofileifexist([[C:/Users/username/Saved Games/DCS/Mods/Scripts/example2.lua]])
      "
    `);
	});

	it("should include paths", async () => {
		expect(result).toContain("C:/Users/username/Saved Games/DCS/Mods/Scripts/example.lua");
		expect(result).toContain("C:/Users/username/Saved Games/DCS/Mods/Scripts/example2.lua");
	});
});
