import { getLogger } from "log4js";
import { posixpath } from "./posixpath.ts";

const logger = getLogger("generateDropzoneMissionScriptingScript");

const FILE_HEADER = `\
-- This file is automatically generated by DCS DROPZONE
-- Do not edit this file manually as it will be overwritten

function dofileifexist(filePath)
    local file = io.open(filePath, "r")
    if file then
        env.info("[dcs-dropzone] - Running dofile: " .. filePath)
        file:close()
        dofile(filePath)
    else
        env.warning("[dcs-dropzone] - Attempted to dofile but file was not found: " .. filePath)
    end
end
`;

const getLineForScript = (id: string, symlinkPath: string) => `\
-- ${id}
dofileifexist([[${symlinkPath}]])
`;

/**
 * Generates a script to run lua files for the provided items.
 *
 * This function creates a script that contains commands to remove directories or delete files
 * based on the provided list of uninstallable items.
 *
 * @param {{id: string, path: string}[]} paths - A list of paths to remove.
 * @returns {string} The generated uninstaller script.
 */
export function generateDropzoneMissionScriptingScript(paths: { id: string; path: string }[]): string {
	const content: string[] = [];

	// eslint-disable-next-line prefer-const
	for (let { id, path } of paths) {
		path = posixpath(path); // Must convert to posix path for lua script as windows paths would need to be escaped
		try {
			logger.debug(`Adding dofile for: ${path}`);
			content.push(getLineForScript(id, path));
		} catch (error) {
			logger.error(`Failed to get stats for path: ${path}`, error);
		}
	}

	return `${FILE_HEADER}\n-- ## Start of Scripts ##\n${content.join("\n")}`;
}
